name: .NET NUnit CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Or 7.0.x/6.0.x depending on your project

    - name: List repo files
      run: ls -R

    - name: Change Directory
      run: cd ./ECommerceApp

    - name: Restore dependencies
      run: dotnet restore ./ECommerceApp/ECommerceApp.sln

    - name: Build
      run: dotnet build ./ECommerceApp/ECommerceApp.sln --configuration Release

    - name: Run Login Tests
      run: dotnet test ./ECommerceApp/ECommerceApp.sln --filter "FullyQualifiedName~AllProductsAreDisplayed" --configuration Release

    - name: Show current working directory
      run: pwd

    - name: List contents of bin/Release/net8.0
      run: ls -R ./ECommerceApp/bin/Release/net8.0

    
    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with: 
        name: ExtentReports
        path: ./ECommerceApp/bin/Release/net8.0/Reports/