name: .NET NUnit CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Or 7.0.x/6.0.x depending on your project

    - name: Install Node.js
      uses: actions/setup-node@v4
      with: 
        node-version: '20'

    - name: Install Node dependencies
      working-directory: ./node-server
      run: npm install

    - name: Start Node test data server
      working-directory: ./node-server
      run: |
        nohup npm start &
        sleep 5

    - name: Change Directory
      run: cd ./ECommerceApp

    - name: Restore dependencies
      run: dotnet restore ./ECommerceApp/ECommerceApp.sln

    - name: Build
      run: dotnet build ./ECommerceApp/ECommerceApp.sln --configuration Release

    - name: Run Login Tests
      run: dotnet test ./ECommerceApp/ECommerceApp.sln --configuration Release

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with: 
        name: ExtentReports
        path: ./ECommerceApp/bin/Release/net8.0/Reports/